---
###############################################################################
# Configuration of OpenStack user environment for Performance Prototype
# Platform (P-cubed).

# Path to create virtualenv in which to install python dependencies.
#p3_venv:

# List of OpenStack projects. Format is as required by the stackhpc.os-projects
# role.
p3_projects:
  - "{{ p3_project }}"

# Definition of the p3 project. Format is as required by the
# stackhpc.os-projects role.
p3_project:
  name: p3
  description: SKA SDP Performance Prototype Platform (P-cubed)
  project_domain: default
  user_domain: default
  users: "{{ p3_users }}"
  keypairs: "{{ p3_keypairs }}"
  quotas: "{{ p3_quotas }}"

# List of users in the p3 project. Format is as required by the
# stackhpc.os-projects role.
p3_users:
  - name: ben
    password: ben
    roles: "{{ p3_user_roles }}"
  - name: chris
    password: chris
    roles: "{{ p3_user_roles }}"
  - name: fred
    password: fred
    roles: "{{ p3_user_roles }}"
  - name: john
    password: john
    roles: "{{ p3_user_roles }}"
  - name: mark
    password: mark
    roles: "{{ p3_admin_roles }}"
  - name: nijin
    password: nijin
    roles: "{{ p3_user_roles }}"
  - name: paul
    password: paul
    roles: "{{ p3_admin_roles }}"
  - name: steve
    password: steve
    roles: "{{ p3_admin_roles }}"
  - name: stig
    password: stig
    roles: "{{ p3_admin_roles }}"
  - name: vlad
    password: vlad
    roles: "{{ p3_user_roles }}"

# List of roles to apply to admin users in the p3 project.
p3_admin_roles:
  - admin
  - heat_stack_owner

# List of roles to apply to admin users in the p3 project.
p3_user_roles:
  - heat_stack_owner

# List of keypairs to register in the p3 project.
p3_keypairs: []

# Dict of quotas to set for the p3 project.
p3_quotas:
  cores: -1
  floating_ips: -1
  injected_files: -1
  injected_file_size: -1
  instances: -1
  key_pairs: -1
  fixed_ips: -1
  ram: -1
  secgroup_rules: -1
  secgroups: -1

###############################################################################
# Configuration of networks, subnets and routers for P-cubed.

# List of networks in the p3 project. Format is as required by the
# stackhpc.os-networks role.
p3_networks:
  - "{{ p3_network }}"

# P3 internal network name.
p3_network_name: "p3-internal"

# P3 internal network.
p3_network:
  name: "{{ p3_network_name }}"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  shared: False
  # Subnet configuration.
  subnets:
    - "{{ p3_subnet }}"

# P3 internal subnet.
p3_subnet:
  name: "{{ p3_network_name }}"
  cidr: "10.0.0.0/24"
  gateway_ip: "10.0.0.1"
  allocation_pool_start: "10.0.0.2"
  allocation_pool_end: "10.0.0.254"

# List of routers in the p3 project. Format is as required by the
# stackhpc.os-networks role.
p3_routers:
  - "{{ p3_router }}"

# P3 router.
p3_router:
  name: "{{ p3_network_name }}"
  network: "ilab"
  interfaces:
    - "{{ p3_subnet.name }}"

###############################################################################
# Configuration of nova flavors for P-cubed.

# List of nova flavors in the p3 project. Format is as required by the
# stackhpc.os-flavors role.
p3_flavors:
  - "{{ p3_flavor_compute_A }}"
  - "{{ p3_flavor_compute_B }}"
  - "{{ p3_flavor_storage_A }}"
  - "{{ p3_flavor_storage_B }}"
  - "{{ p3_flavor_compute_A_magnum }}"

# ALaSKA standard compute node.
p3_flavor_compute_A:
  name: "compute-A"
  ram: 131072
  disk: 371
  vcpus: 64

# ALaSKA high memory compute node.
p3_flavor_compute_B:
  name: "compute-B"
  ram: 524288
  disk: 371
  vcpus: 64

# ALaSKA disk & NVMe based storage nodes.
p3_flavor_storage_A:
  name: "storage-A"
  ram: 131072
  disk: 577
  vcpus: 48

# ALaSKA SSD-based storage nodes.
p3_flavor_storage_B:
  name: "storage-B"
  ram: 131072
  disk: 17877
  vcpus: 48

# Flavor to use for OpenStack magnum baremetal container clusters. Maps to the
# ALaSKA standard compute nodes, and provides an ephemeral disk partition for
# use by container storage.
p3_flavor_compute_A_magnum:
  name: "compute-A-magnum"
  ram: 131072
  disk: 271
  vcpus: 64
  ephemeral: 100
